### ISSUE TITLE
Get better names for list parents

### ISSUE THREAD

**Issue by danrabbit** [elementary/tasks#1]
Right now we get what looks like an ID or we get foo-stub. I'm sure there's a way to get human-readable names for where these lists come from.

**Comment by danrabbit** [comment]
Okay so it looks like these parents are E.Sources, so we just have to figure out the magic registry constant to list them

**Comment by danrabbit** [comment]
Made progress getting the display name for collection accounts using `E.SourceRegistry.find_extension ()`, but I'm not sure how I can get the right source extension constant to query without guessing or trying all of them

**Comment by marbetschar** [comment]
@danrabbit is there anything left to be done on this issue?

**Comment by marbetschar** [comment]
Closing because I think it works good enough. Feel free to reopen if you think otherwise.
