### ISSUE TITLE
App Icon is too large

### ISSUE THREAD

**Issue by marbetschar** [elementary/tasks#112]
The Tasks App Icon is significantly higher compared to other elementary Apps.

Apart from its size, I'm not a huge fan of the icon at all - it is basically just a checkmark in a weird greenish color, but as I'm not a designer I'll leave this up to @elementary/ux :)

![Screenshot from 2020-04-14 13-28-08](https://user-images.githubusercontent.com/392542/79220296-071e4b80-7e54-11ea-92d8-c695f4c82875.png)

**Comment by cassidyjames** [comment]
Well, yeah, if you compare it to short square icons, it will be taller. :smile: But compare it to taller icons like Code or calculator and you can see it fits in with the general icon guidelines. See also: https://elementary.io/docs/human-interface-guidelines#shape

**Comment by marbetschar** [comment]
@cassidyjames mhm, for some weird reason I never noticed Code has a taller icon - but immediately noticed it upon first run of Tasks. And thats despite the fact both Apps reside in my Dock for ages.

Well then, will close this issue for now as I guess you guys are fine with the design too. So it's maybe just me not being a fan of it 😅️

**Comment by Fatih20** [comment]
@cassidyjames Is the current icons is fixed and won't be subject to change? Otherwise, I'd like to design the icon of this app.

**Comment by cassidyjames** [comment]
@Fatih20 you're welcome to propose something, but changing the icon isn't a high priority.

**Comment by Suzie97** [comment]
![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585431-8cc13080-736e-11eb-872c-8862d14caceb.png)

How about this one??

**Comment by Suzie97** [comment]
> ![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585431-8cc13080-736e-11eb-872c-8862d14caceb.png)
> 
> How about this one??
> 
> I can share the figma link for this and you guys can do any changes to the size or anything you want.

Maybe the devs know a way to match the colors of the ticks and the lines with the accent color of the user. That would be a cool feature.

**Comment by Fatih20** [comment]
> ![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585431-8cc13080-736e-11eb-872c-8862d14caceb.png)
> 
> How about this one??

Have you seen how it looks when the app is on the dock? I designed some icons and from my experience, many of the elements there would be barely visible because the icon on the dock is pretty small.

**Comment by Suzie97** [comment]
> > ![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585431-8cc13080-736e-11eb-872c-8862d14caceb.png)
> > How about this one??
> 
> Have you seen how it looks when the app is on the dock? I designed some icons and from my experience, many of the elements there would probably be barely visible because the icon on the dock is pretty small.

I haven't tried it out, but I think it will look similar to the new macOS icons with the 3d effects. I designed an icon for Signal using the same effects I used in this one and it looks pretty good.

**Comment by Fatih20** [comment]
> > > ![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585431-8cc13080-736e-11eb-872c-8862d14caceb.png)
> > > How about this one??
> > 
> > 
> > Have you seen how it looks when the app is on the dock? I designed some icons and from my experience, many of the elements there would probably be barely visible because the icon on the dock is pretty small.
> 
> I haven't tried it out, but I think it will look similar to the new macOS icons with the 3d effects. I designed an icon for Signal using the same effects I used in this one and it looks pretty good.

I assume this icon is 128. Could you pixel-fit it to 48 and try using [this app](https://appcenter.elementary.io/com.github.donadigo.appeditor) to see how it looks on the dock?

**Comment by Suzie97** [comment]
![Screenshot from 2021-02-20 20-08-50](https://user-images.githubusercontent.com/68198116/108599516-9de25f80-73b7-11eb-83c6-50e1b3ff8382.png)

It doesn't look that good in the dock. I think

> > > > ![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585431-8cc13080-736e-11eb-872c-8862d14caceb.png)
> > > > How about this one??
> > > 
> > > 
> > > Have you seen how it looks when the app is on the dock? I designed some icons and from my experience, many of the elements there would probably be barely visible because the icon on the dock is pretty small.
> > 
> > 
> > I haven't tried it out, but I think it will look similar to the new macOS icons with the 3d effects. I designed an icon for Signal using the same effects I used in this one and it looks pretty good.
> 
> I assume this icon is 128. Could you pixel-fit it to 48 and try using [this app](https://appcenter.elementary.io/com.github.donadigo.appeditor) to see how it looks on the dock?

![Screenshot from 2021-02-20 20-08-50](https://user-images.githubusercontent.com/68198116/108599516-9de25f80-73b7-11eb-83c6-50e1b3ff8382.png)

It doesn't look that great in the dock. A more simplified icon with better contrast would be nice I guess.

**Comment by Suzie97** [comment]
@Fatih20, can you share some of your icon ideas??

**Comment by Fatih20** [comment]
> @Fatih20, can you share some of your icon ideas??

They wound up designing a new icon for the app.
