### ISSUE TITLE
Can't add task with no tasks

### ISSUE THREAD

**Issue by cassidyjames** [elementary/tasks#114]
When there are no tasks yet, we get an alert view without a way to add a new one.

![image](https://user-images.githubusercontent.com/611168/79375990-bd4a6980-7f16-11ea-874a-5fb26e0c7091.png)

**Comment by marbetschar** [comment]
@cassidyjames actually there is a task functionality in PR #97 - but its not reviewed yet.

**Comment by cassidyjames** [comment]
@marbetschar if the fix hasn't been merged to master, please leave the issue open and note `fixes #114` in the PR.
