### ISSUE TITLE
Add missing palette colors to color button list

### ISSUE THREAD

**Issue by micahilbery** [elementary/tasks#117]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

We've added new colors to the palette (bubblegum and mint) and they are missing from the colors selectable for tasks.

**Comment by 4jNsY6fCVqZv** [comment]
I would like to work on this issue to contribute a solution. It would be my first contribution to a project ever. Might need some feedback from you then. How do you feel about it?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv you're more than welcome to. :) It looks like ListSettingsPopover.vala is where you'll want to address this.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames Thank you! Should I also make changes in the ColorButton.css as well?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv yep it looks like you will need to.

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames I have to fork the project first to be able to make a Pull Request?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv yep! If it's a simple enough change, you can use GitHub's web UI to make it and it will automatically create a fork on your account.

**Comment by 4jNsY6fCVqZv** [comment]
I'm just wondering why some colors in the current list use the value 300 and others 500.
How do you select which color gradient you want to include in the Task palette?

**Comment by cassidyjames** [comment]
@4jNsY6fCVqZv probably their contrast with white (since that's the color of the checkmark that gets overlaid).

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames 

>  probably their contrast with white

Is this something I can check in advance?

> (since that's the color of the checkmark that gets overlaid).

At this point, is it important to think about a dark UI preference for the system UI? Or will this come in a later step?

I also wonder why the colors are named differently in the ColorButton.css than in the palette on https://elementary.io/de/brand.
For example .color-button.green instead of .color-button.lime. Only with slate it is the same.

**Comment by cassidyjames** [comment]
> Is this something I can/should check in advance?

You can use [Harvey](https://appcenter.elementary.io/com.github.danrabbit.harvey/) to check color contrast, and optionally [Palette](https://appcenter.elementary.io/com.github.cassidyjames.palette/) for quicker access to the palette colors. Or, you can try the 500 levels and if it looks low-contrast, we can switch them to 300. :smile: 

>At this point, is it important to think about a dark UI preference for the system UI as well? Or will this come in a later step?

Probably good to keep in mind, but I believe the foreground color would be the same in the dark style.

>I also wonder why the colors are named differently in the ColorButton.css than in the palette

Yeah, my guess is just us not being super consistent. We could rename here to use the palette color names, but it's not a huge deal—if you want to add the new ones as "mint" and "bubblegum" that's fine, and we can clean up the others at the same time or later.

**Comment by 4jNsY6fCVqZv** [comment]
Thank you, now I have a good feeling and I am ready to start!

> and we can clean up the others at the same time

I'll solve it too. Then it's super consistent. :smile:

**Comment by 4jNsY6fCVqZv** [comment]
@cassidyjames 

> and optionally Palette for quicker access to the palette colors

Becomes much more comfortable when https://github.com/cassidyjames/palette/issues/48 is solved as well.

**Comment by cassidyjames** [comment]
Ah, you're right. :sweat_smile:

**Comment by marbetschar** [comment]
Closing because this was merged in #137
