### ISSUE TITLE
Missing icon sizes

### ISSUE THREAD

**Issue by cassidyjames** [elementary/tasks#133]
We just have 64px at the moment.

- [ ] 16
- [ ] 24
- [ ] 32
- [ ] 48
- [x] 64
- [ ] 128

cc @elementary/ux :wink:

**Comment by hezral** [comment]
i'd love to help but is the icon design final?

**Comment by danrabbit** [comment]
@hezral Not particularly. I mostly did it as a placeholder. If you have a better design please feel free to propose it :)

**Comment by hezral** [comment]
Thanks, that changes the task then. Anyway, i see @andirsun already made a PR for this so i'll back down for now :)
