### ISSUE TITLE
The Gtk.Paned separator disappears when resizing.

### ISSUE THREAD

**Issue by alainm23** [elementary/tasks#18]
For some reason the separator of the Gtk.Paned disappears when it is dragged, this can be a problem on the stylesheet, I worked last night looking for a solution.

![nn](https://user-images.githubusercontent.com/33765137/62789084-d77d9f00-ba8d-11e9-9301-2bd3524e09fe.gif)

**Comment by alainm23** [comment]
This is my solution:

![n](https://user-images.githubusercontent.com/33765137/62788909-7e157000-ba8d-11e9-8b48-51f1f889c71a.gif)

**Comment by danrabbit** [comment]
I'm not able to reproduce this issue. Are you using the stylesheet from master?

**Comment by alainm23** [comment]
Yes, I use the default stylesheet installed

**Comment by ryonakano** [comment]
It sounds related to this issue: https://github.com/elementary/files/issues/617 (Files also uses Gtk.Paned there)

**Comment by alainm23** [comment]
It seems to be a mistake in my graphics with NVIDIA

**Comment by santileortiz** [comment]
This also happened to me in Iconoscope, I also added some custom CSS to fix it. See https://github.com/santileortiz/Iconoscope/blob/f1b8b2e9713de7bf79254b26c61e909a1640bc0f/gtk_utils.c#L204.
