### ISSUE TITLE
A more creative icon design

### ISSUE THREAD

**Issue by hanaral** [elementary/tasks#190]
## Problem

It's just a square with a small-ass tick in the center. This is some pretty inaccesible iconography, users should not have to actually think what it is.

## Prior Art

Something like this maybe?
![photo_2021-02-14_15-00-29](https://user-images.githubusercontent.com/58219504/107880231-6fefad80-6ed5-11eb-8363-d4c7b6c165fa.jpg)

**Comment by marbetschar** [comment]
There were already some discussions about the icon - so you might want to follow up with the involved people there:

- https://github.com/elementary/tasks/pull/166
- https://github.com/elementary/tasks/issues/112

Speaking of discussions: This type of question might be better suited there. However, I don't seem to be able to move this issue to discussions in the GitHub iOS app 🤷‍♂️

**Comment by hanaral** [comment]
Ok I spent too much time on this but I can't say I didn't enjoy it.

![io elementary tasks](https://user-images.githubusercontent.com/58219504/107892610-3727f680-6f1e-11eb-8fec-06786fb6953e.png)

**Comment by Suzie97** [comment]
![Tasks Icon](https://user-images.githubusercontent.com/68198116/108585628-66e85b80-736f-11eb-8603-1d8a7913037e.png)

I designed this one. If the color of the ticks matches with the accent color, it would be niceeee.

**Comment by danrabbit** [comment]
Just adding a couple of iterations from @micahilbery and myself:

![image](https://user-images.githubusercontent.com/7277719/108635275-7c26be00-7433-11eb-9703-36249b4bff39.jpeg)

![image](https://user-images.githubusercontent.com/7277719/108635279-7fba4500-7433-11eb-8446-b6105a8a08b2.jpeg)

**Comment by hanaral** [comment]
I'm thinking that it would probably convey the right metaphor, look sleek af and also be quite accessible to have the one from Micah but with some 4 thick dark grey ring-binders on the right. 


![64](https://user-images.githubusercontent.com/58219504/108725851-b4ef9180-751e-11eb-97df-3d71ecb9454f.png)
[And here is the SVG](https://gist.github.com/hanaral/4bfceff06d9cd8765dee49e121f481da)
