### ISSUE TITLE
Design when packaged as Flatpak is wrong

### ISSUE THREAD

**Issue by marbetschar** [elementary/tasks#194]
When I package the Tasks app on elementary 6 Odin, the design of the app looks wrong. Seems like the Stylesheet does not have any effect on it at all. Is there a dependency missing in the `io.elementary.tasks.yml`?

![Screenshot from 2021-02-16 21-49-30](https://user-images.githubusercontent.com/392542/108120043-f86e7980-70a0-11eb-92cb-2e9654c7484e.png)

FWIW: I built, installed and started Tasks with the following commands:

```bash
flatpak --user install flathub \
  org.gnome.Sdk//3.38 \
  io.elementary.BaseApp//juno-20.08
flatpak-builder --force-clean build io.elementary.tasks.yml
flatpak-builder --install --user --force-clean build io.elementary.tasks.yml 
flatpak run io.elementary.tasks 
```

**Comment by Marukesu** [comment]
It's because we don't package the new stylesheet in Flatpak or BaseApp, but we have the old stylesheet in BaseApp. you need use `flatpak run --env=GTK_THEME=elementary io.elementary.tasks` for that.

**Comment by marbetschar** [comment]
@Marukesu when I start Tasks with your command it looks indeed better. However, is is still different than when using the "old" package install. Also it does not seem to respect the Dark Mode system settings (see screenshots below).

Are those issues already tracked somewhere? Not quite sure where the right place would be for this kind of issues.

**Flatpak**

![Screenshot from 2021-02-17 14-01-14](https://user-images.githubusercontent.com/392542/108208381-44650100-7129-11eb-8164-63cdd9b0d975.png)

**Without Flatpak**

![Screenshot from 2021-02-17 14-01-43](https://user-images.githubusercontent.com/392542/108208393-49c24b80-7129-11eb-81cf-40174f95dd83.png)

**Comment by Marukesu** [comment]
>when I start Tasks with your command it looks indeed better. However, is is still different than when using the "old" package install. Also it does not seem to respect the Dark Mode system settings (see screenshots below).

Yeah, `GTK_THEME` overrides the loaded theme, so the app don't change it when asked, you can use `GTK_THEME=elementary:dark` for the dark theme, I think.

>Are those issues already tracked somewhere? Not quite sure where the right place would be for this kind of issues.

Well, there's a PR for that in the elementary runtime [here](https://github.com/elementary/flatpak-platform/pull/11).

**Comment by marbetschar** [comment]
Nice one! Thanks for the clarifications, I don't have any experience yet how this Flatpak packaging stuff comes together. Will close this issue, since its not Tasks related.
