### ISSUE TITLE
Note that exceeds the length of the window truncates note

### ISSUE THREAD

**Issue by phase1geo** [elementary/tasks#231]
## What Happened
I entered a note that had enough text such that the entirety of the note could not be displayed on one line.  The string gets truncated to show the end of the note.

## Expected Behavior
I think that either the entire note should be displayed, an ellipsis should be displayed, a tooltip should display the entirety of the note in a tooltip (with formatting applied), or omit the display of the note, showing a note icon instead.

**Task Edit:**

![image](https://user-images.githubusercontent.com/22555565/116798468-144dbd00-aadf-11eb-88c0-a04ef6fe66a6.png)

**Task After Edit:**

![image](https://user-images.githubusercontent.com/22555565/116798486-52e37780-aadf-11eb-9e1a-5bd6a52c49c9.png)

## Platform Information
* elementary 6.0 Beta
* Latest release

**Comment by mcclurgm** [comment]
This seems to be a layout bug of some sort. The label is set to ellipsize, but it's not doing that for some reason. There must be some other widget in the TaskRow that has a minimum width, which the label then inherits.

**Comment by mcclurgm** [comment]
Not actually closed in #245
