### ISSUE TITLE
The app icon is taller than others inside Plank

### ISSUE THREAD

**Issue by megatux** [elementary/tasks#232]
Trying beta here.
A cosmetic issue, but, this new app icon looks odd to me because it's taller than the rest

![2021-05-03-131730_1232x261_scrot](https://user-images.githubusercontent.com/850020/116902894-1a908600-ac12-11eb-9c6e-2b3e9a01dcc5.png)

less height, just a couple of pixels would be better IMHO. WDYT?

**Comment by hanaral** [comment]
Isn't this just the 'upright rectangle' icon sizing based on @micahilbery 's template

**Comment by danirabbit** [comment]
Fixed in #335
