### ISSUE TITLE
Cannot launch tasks with latest nvidia driver

### ISSUE THREAD

**Issue by selwynorren** [elementary/tasks#262]
## What Happened
Tasks fails to launch and after some investigations with various Nvidia drivers the log shows differently. on my laptop where I have the 390 driver installed the app launches without issues

On my desktop I have the 470 driver installed and I get teh following if I run it using the terminal
```
Gtk-Message: 10:42:20.515: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:42:20.516: Failed to load module "canberra-gtk-module"

(io.elementary.tasks:2): Clutter-CRITICAL **: 10:42:20.870: Unable to initialize Clutter: Unable to initialise the Clutter backend: no available drivers found.

(io.elementary.tasks:2): Clutter-WARNING **: 10:42:21.032: Missing Cogl context: was Clutter correctly initialized?

(io.elementary.tasks:2): Cogl-WARNING **: 10:42:21.148: Failed to create default context: Unable to create suitable GL context

(io.elementary.tasks:2): CoglPango-CRITICAL **: 10:42:21.148: cogl_pango_font_map_set_resolution: assertion '(((__extension__ ({ GTypeInstance *__inst = (GTypeInstance*) ((font_map)); GType __t = ((pango_cairo_font_map_get_type ())); gboolean __r; if (!__inst) __r = (0); else if (__inst->g_class && __inst->g_class->g_type == __t) __r = (!(0)); else __r = g_type_check_instance_is_a (__inst, __t); __r; }))))' failed

(io.elementary.tasks:2): GLib-GObject-CRITICAL **: 10:42:21.148: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
```
If I downgrade the driver to 460 (I cant go below that) then it still fails to launch however the only error I get is:
```
Gtk-Message: 10:42:20.515: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:42:20.516: Failed to load module "canberra-gtk-module"

(io.elementary.tasks:2): GLib-GObject-CRITICAL **: 10:42:21.148: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
```
So based on that I am assuming that its a display driver issue as the laptop and desktop are both running the daily snapshot with all updates active.

I have also tested if I completely remove the nvidia drivers from my system, then tasks fully launches but I get a different error in terminal with no nvidia drivers, however I am unsure if this is important or not
```
Gtk-Message: 10:56:39.138: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:56:39.140: Failed to load module "canberra-gtk-module"
libGL error: MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
```

## Expected Behavior
Tasks should launch

## Steps to Reproduce
Have the latest nvidia drivers installed
Using terminal run the following command
`flatpak run io.elementary.tasks`

### Logs
Listed above

## Platform Information
elementary OS 6 Early Access
Built on Ubuntu 20.04.1 LTS
Linux 5.8.0-63-generic

**Comment by jakubrosa** [comment]
I have a similar issue, I also can't run Tasks, but I have the same error message on 460 and 470 versions of the NVIDIA driver.

`Gtk-Message: 14:15:22.718: Failed to load module "canberra-gtk-module`
`Gtk-Message: 14:15:22.719: Failed to load module "canberra-gtk-module"`

`(io.elementary.tasks:2): GLib-CRITICAL **: 14:15:22.752: g_strsplit: assertion 'string != NULL' failed`

On my laptop without NVIDIA GPU it also works flawless.

**Comment by selwynorren** [comment]
So 8 discovered that if I set the permissions for the app (available in the settings) and I activate the hardware acceleration. Then the app works. I still have other issues, but now at least it launches. Not sure if this should be set as on by default as I see other apps already have that activated without my doing. See if this works for you.

**Comment by jakubrosa** [comment]
I found that if I create missing directories which causes flatpaks unable to install

**Comment by jakubrosa** [comment]
> So 8 discovered that if I set the permissions for the app (available in the settings) and I activate the hardware acceleration. Then the app works. I still have other issues, but now at least it launches. Not sure if this should be set as on by default as I see other apps already have that activated without my doing. See if this works for you.

Yeah, it works for me as well, it looks like it is a permission issue for access to NVIDIA GPU acceleration. Thank you!

**Comment by davidmhewitt** [comment]
Thanks for the info everyone, I can confirm this.

I've opened #265 which will give the application that permission by default.
