### ISSUE TITLE
Window Control Button Layout

### ISSUE THREAD

**Issue by fayjie92** [elementary/tasks#273]
## Problem
The current Tasks interface does not consider the window control button (layout) settings. It would be consistent for a user to have the same button layout when changed to other styles (suppose mac style). I prefer to have the minimize button. 

## Proposal
The 'Planner' app provides the settings to control it manually. Implementing something similar would solve the problem (or even in a global way that follows the system window button layouts automatically).
![tasks vs planner (1)](https://user-images.githubusercontent.com/32283602/129492783-10802076-2676-4b8e-8c12-e95818e10c0a.png)

**Comment by danrabbit** [comment]
It looks like we need to use a https://valadoc.org/libhandy-1/Hdy.HeaderGroup.html here so we can avoid hardcoding the button layout
