### ISSUE TITLE
Translation to Brazilian Portuguese is incorrect

### ISSUE THREAD

**Issue by OverlandAcorn09** [elementary/tasks#275]
## Translation to Brazilian Portuguese is incorrect
It is a simple issue, only one word need to be corrected: oinline -> online

## Steps to Reproduce

1. Change the language to Brazilian Portuguese: System Settings -> Language and Region -> Portuguese. (After that logout and login again to apply the changes.)
![1](https://user-images.githubusercontent.com/85706899/129805377-2299f99b-7cae-4ee8-a554-d896d4169a77.png)

2. Open tasks and click at "Adicionar lista de tarefas...", you'll find the word "oinline" that should be "online".
![2](https://user-images.githubusercontent.com/85706899/129806241-5114cfa3-442e-4515-996d-3618b0615085.png)

## Platform Information

elementaryOS 6.0 Odin
Tasks version: 6.0.2
![platform_info](https://user-images.githubusercontent.com/85706899/129806776-c3821bb9-ce40-4c80-8f39-f5c81cbe56b3.png)

(This is my first mistake here so I'm sorry if anything is wrong)

**Comment by JohnDumpling** [comment]
You can write translation suggestions on the Weblate platform - it is accessible from the official elementary.io website from the Get Involved tab. The translator(s) will be notified about this change.

**Comment by OverlandAcorn09** [comment]
> You can write translation suggestions on the Weblate platform - it is accessible from the official elementary.io website from the Get Involved tab. The translator(s) will be notified about this change.

Ok thank you!! I'll close this issue now
