### ISSUE TITLE
Duplicate Tasks app that does not work correctly

### ISSUE THREAD

**Issue by JohnDumpling** [elementary/tasks#276]
## What Happened
The Tasks app was working flawlessly before one of the system updates broke it. Now, when I open the app, nearly blank window shows up with misplaced window controls. In the AppCenter, the app shows as **not installed**. When I install it for the second time, it fails to launch and crashes. The first (older) Tasks app also can't be uninstalled.

## Expected Behavior
The Tasks app should fully work after opening it.
It should be possible to uninstall it.
It should show as **installed** in the AppCenter.
It shouldn't be possible to install a duplicate app.

## Steps to Reproduce
1. Launch the Tasks app.

2. A window with misplaced elements should show up.
![image](https://user-images.githubusercontent.com/89086803/129856991-10a024c4-ae35-445b-bde3-5f9e7e7ecde4.png)

3. Now close the Tasks app and open AppCenter.

4. Search for "Tasks" in the search bar.

5. Click the "Free" install button and install the duplicate app. (As you can see, the older app cannot be uninstalled.)
![image](https://user-images.githubusercontent.com/89086803/129856929-2b22e8e4-edda-48de-9a6e-c10d5a92b37c.png)

6. Now open the app from the AppCenter. It should appear on the dock as a duplicate app. After a while, it will crash and disappear. 
![image](https://user-images.githubusercontent.com/89086803/129856961-913b851f-b79b-44d4-b28a-59e60d61b8b7.png)

### Logs
Not sure how to include logs (no experience with code / terminal, tried to follow the tutorial but couldn't understand)

## Platform Information
Running elementary OS Odin (dual-booting Windows 10)
Computer: Lenovo Legion 5
Processor: AMD Ryzen 7 4800h + integrated Radeon Graphics
Graphics card: nVidia GTX 1660 ti mobile (nvidia-driver-470 from the AppCenter - 470.57.02)
Memory: 16GB
Storage: 512GB SSD

Duplicate (crashing) Tasks app ver. 6.0.0
Older (broken) Tasks app ver. unknown (does not show up in the AppCenter)

**Comment by JohnDumpling** [comment]
**Okay, I think I know what caused this issue.** When I first installed eOS 6, there was a default driver preinstalled. But as the Davinci Resolve video editor didn't support it, I downloaded the nVidia 470 driver. This has caused the screen brightness slider to stop working, and I had to find a tutorial how to fix it. I followed this [video](https://www.youtube.com/watch?v=N4iN6lCyE6A) and after applying all the commands, I changed the BIOS graphics settings from Discrete to Switchable. I think that all of this tweaking **has broken the Tasks app installation** and caused it to incorrectly display and made it impossible to uninstall through the GUI.

When I download the duplicate Tasks app, it crashes when I try to launch it, which seems like the issue already mentioned in this feedback forum **(nVidia graphics card does not work with Tasks app)**.

**Comment by marbetschar** [comment]
Sorry to hear to ran into troubles! Nvidia is always fun, huh? ;)

I will close this in favor of https://github.com/elementary/tasks/issues/268, but feel free to create a new issue if there's something more you need help with!

**Comment by JohnDumpling** [comment]
Oh yes, I had so much trouble with Nvidia drivers :D 
Btw, do you know how can I uninstall the broken Tasks app? Maybe there is some command for it? Because when I try to uninstall it through the Uninstall button, an error shows up (sometimes I can't even press the button, as it is grayed out):
![image](https://user-images.githubusercontent.com/89086803/130409087-81a44b06-037e-44a6-a1eb-eec69781d9df.png)

**Comment by marbetschar** [comment]
@JohnDumpling you should be able to uninstall the Tasks app through the terminal with the following command:

```bash
flatpak uninstall io.elementary.tasks
```

**Comment by JohnDumpling** [comment]
Thank you very much, now I'll close this issue.
