### ISSUE TITLE
Provide refresh/reload button

### ISSUE THREAD

**Issue by Suzie97** [elementary/tasks#306]
### Problem

Currently, Tasks does not seem to refresh tasks live when things are changed in the caldav backend. This makes it hard, as I need to open evolution and then do the refresh manually.

### Proposal

Provide a refresh button to reload/refresh tasks. Ideally, doing it live when things change in the backend would be neat, but for now, atleast providing a button to do looks important.

### Prior Art (Optional)

elementary OS Mail App
Apple Reminders reloads automatically when things change in the backend

**Comment by metalune1** [comment]
Why hasn't this ever been worked on?
