### ISSUE TITLE
Improve time zone handling: floating by default?

### ISSUE THREAD

**Issue by mcclurgm** [elementary/tasks#312]
### Problem

Tasks currently has an ill-defined way of handling timezones. (See elementary/wingpanel-indicator-datetime#252). It assigns reminders a timezone of UTC, but treats that as local. We should define the way it works.

Also, it includes timezones in reminders by default. So if you move between time zones, your reminders will change. I think that in most cases that you want a reminder for a task, it's the time of day that matters, not the time on a universal clock. 
For example, taking trash out, cooking, taking medicine, or other such tasks are all based on the time of day where you are. As an extreme example, if I move across the world, I wouldn't expect to start cooking dinner at 6 am instead of 6 pm. This reminder makes more sense as a floating timezone. 
Home examples are easier to say that they should be based on time of day not universal time. Work tasks tasks are less clear.

### Proposal

The most basic thing we could do is assign tasks the local timezone. This would fix bugs with treating UTC as local and not converting.

I would suggest that we leave task reminders with a floating timezone. This would fix the issues with changing reminder time when changing timezones.

However, making all tasks floating may have some drawbacks. There will always be cases where people will want to set a reminder at a certain universal time and have the time of day change. Also, if you share a task list with someone else in a different timezone, you'll get reminders at different times. The question then becomes which case do we think is more likely: universal or time of day?

We could implement a way of selecting a timezone (see Todoist's method for a simplified version of this), but I think that may be more detailed than we need. I don't know how to go about researching this, but I would expect that a floating time will work for most use cases.

I would appreciate design input about this. Implementing the change should be relatively easy, since our backend already supports all the timezone behaviors I'm describing, so the change would be restricted to the UI.

### Prior Art (Optional)

Other tasks apps I use are Things and Todoist. Both use floating times by default (although you can change that in Todoist, see [help article](https://todoist.com/help/articles/set-a-fixed-time-zone-or-floating-time-for-a-task)).

**Comment by marbetschar** [comment]
> I think that in most cases that you want a reminder for a task, it's the time of day that matters, not the time on a universal clock.

I agree. That was always my/the intention of how Tasks should handle datetime information.

> There will always be cases where people will want to set a reminder at a certain universal time and have the time of day change.

I guess there are (edge) cases for everything. IMHO floating times work for the majority of use cases and on top of this we don't need to add another input to the UI.

**Comment by marbetschar** [comment]
In case we'd like to support timezones in the future: Can't we just let the user decide for each task (and/or list) whether they want to interpret the timezone information or treat datetimes as floating? I mean, there's always the possibility to add our own X-prefixed custom properties to a task (and/or list) [like Apple does for manual sorting](https://github.com/elementary/tasks/blob/e367d1aa45fc687713bfe9b7e8f2d93c214d51c1/src/Util.vala#L187-L193) for example.

**Comment by mcclurgm** [comment]
I'm not sure what you mean in the second comment. I agree with your first comment, floating times would cover most of the use cases so I was also thinking that's all we need. If we get many reports about people wanting set timezones, we could implement it later.

But I don't know what you mean by adding a custom property. Telling whether to interpret relative to a specific timezone or as floating is handled directly in `icaltime` and the icalendar spec. It's also handled in the `datetimes_to_icaltime` function. So that doesn't need to be a custom field. I assume there's something I'm misunderstanding?

**Comment by marbetschar** [comment]
> I'm not sure what you mean in the second comment. I agree with your first comment, floating times would cover most of the use cases so I was also thinking that's all we need. If we get many reports about people wanting set timezones, we could implement it later.

Alright, then lets do this! :rocket: 

> But I don't know what you mean by adding a custom property. Telling whether to interpret relative to a specific timezone or as floating is handled directly in `icaltime` and the icalendar spec. It's also handled in the `datetimes_to_icaltime` function. So that doesn't need to be a custom field. I assume there's something I'm misunderstanding?

Nevermind. I don't know a whole lot about the inner workings of timezone conversions in EDS. So the custom property was just an idea I came up with - but of course, we can also go down another route once we really need this.
