### ISSUE TITLE
Flatpaked 6.1.0 was not installed

### ISSUE THREAD

**Issue by meisenzahl** [elementary/tasks#318]
### What Happened?

I just ran a manual `apt dist-upgrade` and got the following error message:

```
Setting up io.elementary.tasks (6.1.0+r1137+pkg11~ubuntu6.1) ...
error: io.elementary.tasks/*unspecified*/stable not installed
```

Tasks is still installed as a native program and not as a flatpak:

```
$ flatpak run io.elementary.tasks
error: app/io.elementary.tasks/x86_64/master not installed
```

### Steps to Reproduce

1. Run `apt update`
2. Run `apt dist-upgrade`
3. You should get a similiar error message as mentioned above

I can reproduce this on another device.

If you already updated you can reproduce this behavior with:

```
apt install --reinstall io.elementary.tasks
```

### Expected Behavior

Tasks 6.1.0 should be installed as Flatpak.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by meisenzahl** [comment]
I have also updated Tasks in a virtual machine via AppCenter. The Flatpak variant was not installed there either.

**Comment by danrabbit** [comment]
Yeah we switched to the deb package a while back because of EDS stuff. There's a postinst script that's supposed to _remove_ the flatpak package, but since it's already not installed it's failing. Removed the script

**Comment by danrabbit** [comment]
Hey @meisenzahl just to confirm, was the package installation actually failing or are you just reporting the log output?

**Comment by meisenzahl** [comment]
The package installation exited with code 0, but Tasks was not installed as a Flatpak.

**Comment by danrabbit** [comment]
@meisenzahl ah okay, that sounds like it was working as intended. The postinst script is meant to _remove_ the Tasks flatpak

**Comment by meisenzahl** [comment]
😅 Sorry for the confusion
