### ISSUE TITLE
Location and Time buttons have white text on light background

### ISSUE THREAD

**Issue by rexbron** [elementary/tasks#333]
Please see the attached screen shots from Fedora 36, the text for adding a date and time, as well as location are white text on a light background.

Version-Release number of selected component (if applicable):

elementary-tasks-6.2.0-1.fc36.x86_64 : Synced tasks and reminders application
Repo        : fedora
Matched from:
Filename    : /usr/bin/io.elementary.tasks

![Screenshot from 2022-05-24 08-13-34-markedup](https://user-images.githubusercontent.com/587341/170036708-f7687eaf-56b5-4733-bab0-b4630a932159.png)
![Screenshot from 2022-05-24 08-13-34](https://user-images.githubusercontent.com/587341/170036712-bbe1b8df-33e3-4ceb-9aaf-2bd59ac34d6d.png)

How reproducible:

Everytime

Steps to Reproduce:
1. Launch Tasks
2. Create new task
3. Observe white on light background label.

**Comment by tintou** [comment]
The application, when used in a Fedora package, need the `elementary-theme` package and the theme to be used.
