### ISSUE TITLE
Tasks automatically opens on system startup

### ISSUE THREAD

**Issue by TomiOhl** [elementary/tasks#369]
### What Happened?

Tasks automatically opens now on system startup showing it's home screen when autostart is enabled.

### Steps to Reproduce

1. Make sure you have Tasks 63.2 and autostart is enabled (by default it is)
2. Restart your device

### Expected Behavior

It should start only in background, shouldn't open the UI

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
It's the same issue as https://github.com/elementary/mail/issues/919, which has a manual solution. But I guess this needs to be fixes properly somehow.

**Comment by TomiOhl** [comment]
So does that mean that I have to remove `/etc/xdg/autostart/io.elementary.tasks-daemon.desktop` for now?
As I see it executes `io.elementary.tasks --background`, but that background option seems to have no effect and starts with the GUI (tested this by manually running the command)

**Comment by danirabbit** [comment]
Hm yeah this should be automatically removed by packaging when you update. I assumed we had it because we’d been installing manually during development

**Comment by Marukesu** [comment]
> …As I see it executes `io.elementary.tasks --background`, but that background option seems to have no effect and starts with the GUI (tested this by manually running the command)

this happens because task is already running, task won't respect the background flag when already launched. you two autostart files (the one in /etc/xdg/autostart and the one created by the portal) are being launched and triggering this conner case.

**Comment by Ivan-Velickovic** [comment]
Removing `sudo rm /etc/xdg/autostart/io.elementary.tasks-daemon.desktop` fixed it for me. Previously I had tried to remove/disable the Tasks startup in `System Settings -> Applications -> Startup` but it had no affect upon reboot. Currently even with `/etc/xdg/autostart/io.elementary.tasks-daemon.desktop` removed, Tasks is still listed as a startup application.

Let me know if you would like me to provide any other information!

**Comment by TomiOhl** [comment]
Thanks @Ivan-Velickovic yes you're right, lenemter already opened #370 that will solve the issue in the same way (delete the file post installation).
Guess if that's correct the same fix can be applied for Calendar, too

**Comment by danirabbit** [comment]
Should be fixed by #370 which was just merged and I'm doing a package build today :tada:
