### ISSUE TITLE
Application crashes when system theme changes

### ISSUE THREAD

**Issue by zeebok** [elementary/tasks#389]
### What Happened?

When the theme changes the in either direction, tasks will crash when trying to change itself

### Steps to Reproduce

1. Open Tasks
2. Update system theme

### Expected Behavior

The app should change its theme with the system

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Duplicate of #372 ?

**Comment by zeebok** [comment]
Oh it is... Though I still see the problem. I am fine with closing this and reopening that if need be.

**Comment by danirabbit** [comment]
It seems to be working okay here on an OS 8 daily :thinking:

**Comment by zeebok** [comment]
> It seems to be working okay here on an OS 8 daily 🤔

Hm yeah, it is working for me there. I will let you make the call if a fix for OS7 should be investigated or to close this.

**Comment by danirabbit** [comment]
Sorry missed that part! I'll spin up a VM and see if I can fix it

**Comment by danirabbit** [comment]
@zeebok I can't confirm a crash here on a fresh OS 7.1 either

**Comment by zeebok** [comment]
Hmm alright. Not sure why I see it then. I say we just close this for now as I am not seeing it on OS8. If it happens again on there, I will re-open.
