### ISSUE TITLE
Edit task details

### ISSUE THREAD

**Issue by marbetschar** [elementary/tasks#56]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

**Edit task details**
It should be possible to edit the task details.

**Describe the solution you'd like**
The edit should take place within a popover form. The popover should be shown if the user either double clicks on a task row, or selects the task row and hits the Enter button. Similar to what Apple Reminders does:

<img width="623" alt="Bildschirmfoto 2019-10-22 um 19 50 10" src="https://user-images.githubusercontent.com/392542/67314597-3b4c2b80-f505-11e9-8959-001e4185cf6d.png">

**Comment by marbetschar** [comment]
Tried to show a popover when the user doubleclicks on a task. Unfortunately I'm not able to kick the event handler off. What am I missing?

I an see the `debug ("1: binding event...");` output, but neither `debug ("2: grid.other key_release");` nor `debug ("3: grid.double-left-click!");`.

The corresponding code:
https://github.com/elementary/tasks/blob/2dbe179baedb18a4f94d24e709f9cf6f9c95a1f2/src/Widgets/TaskRow.vala#L128-L136

**Comment by alainm23** [comment]
You should to use `row_activated` in your Gtk.Listbox instead of `button_press_event`:

listbox.row_activated.connect ((row) => {
    var item = ((Tasks.TaskRow) row);
    item.open_popover ();
}); 

I recommend using `button_press_event` just to open a menu or some special feature. Another recommendation with my experience is that if you use `button_press_event` you will not be able to implement the Drag and Drop feature.

**Comment by alainm23** [comment]
Try:
```
eventbox = new Gtk.EventBox ();
eventbox.expand = true;
eventbox.above_child = false;
eventbox.add (grid);

eventbox.event.connect ((event) => {
    if (event.type == Gdk.EventType.@2BUTTON_PRESS) {
        debug ("3: grid.double-left-click!"); 
    }

    return false;
});
```

**Comment by marbetschar** [comment]
@alainm23 awesome, it works. Thank you very much!! Next stop: Creating a form to edit a task... ;)

**Comment by alainm23** [comment]
Great. If you have any questions let me know, I think I have a little experience in this (I develop a task manager too 😁️)

**Comment by alainm23** [comment]
Can I give you a recommendation? 

You should not create the popover when you create the widget (TaskRow). why?
Drawing all the widgets takes even longer if you have many widgets such as labels, entrys, switch, etc ...
Now you only have some tasks and the creation process is fast, but imagine if you have about 50 or more tasks, the application has to draw each widget and this takes time and most likely its application will freeze.

I had the same problem with Planner and to solve it use this solution. I declare the popover as null and only draw it when the user needs it.
https://github.com/alainm23/planner/blob/master/src/Views/Project.vala#L14
https://github.com/alainm23/planner/blob/master/src/Views/Project.vala#L238

**Comment by marbetschar** [comment]
I'm trying to implement the UI to edit a task within a popover. But I'm stuck, facing the same issue again as in #45: We are not able to access the `ICal.Component` after a subsequent event occurs. This time, I'm trying to pass the component to the newly rendered popover as soon as the user double clicks on a task item. Seems like the `ICal.Component` is already gone at this point in time.

@danrabbit any idea how to properly work with `ICal.Component`? From what I can tell we are stuck without a solution for this.

The code in question is:

https://github.com/elementary/tasks/blob/f6608425bf35d774143f8f304fe774bf77078d1b/src/Widgets/TaskRow.vala#L133-L147

Here's the corresponding `gdb` output:

```
(gdb) run
Starting program: /home/marbetschar/Development/tasks/build/io.elementary.tasks 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe344d700 (LWP 27878)]
[New Thread 0x7fffe1069700 (LWP 27879)]
[New Thread 0x7fffdb131700 (LWP 27893)]
[New Thread 0x7fffda0b3700 (LWP 28002)]
[New Thread 0x7fffd98b2700 (LWP 28003)]
[New Thread 0x7fffc6c30700 (LWP 28071)]

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:33.209: gtk_entry_set_text: assertion 'text != NULL' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:33.266: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:34.017: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:34.418: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:35.219: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:35.627: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:36.429: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:36.833: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:37.312: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed

(io.elementary.tasks:27409): Gtk-CRITICAL **: 00:00:37.550: gtk_render_frame_gap: assertion 'xy0_gap >= 0' failed
[Thread 0x7fffda0b3700 (LWP 28002) exited]
```

**Comment by alainm23** [comment]
you can try creating the Popover out of the click function and when the user clicks send the task and show the Popover

**Comment by marbetschar** [comment]
@alainm23 you're right. The thing is, from the code of the elementary Calendar it seems that we need the `ICal.Component` to be able to update the data:

https://github.com/elementary/calendar/blob/3627c6bd7d05c3638599a52f23f26b550c6c2603/core/Model/CalendarModel.vala#L156-L176

However, there it seems they are working with the `ECal.Component` throughout the app - not the `ICal.Component`. Maybe this works better as it is not marked with `unowned`.... Will give this a shot, maybe that's the missing piece.

**Comment by marbetschar** [comment]
Workaround for now: Introducing a new struct `TaskModel` which receives all needed fields by copy them over from the original `ICal.Component` on the first run. Subsequent access of the data is done on the `TaskModel` object. See commit https://github.com/elementary/tasks/commit/ed8300385eda9d77f9004244c861bc059fd108fa for a detailed list of changes.

are there any concerns about this strategy?

**Comment by alainm23** [comment]
I think it is a very good solution 👍️.

**Comment by marbetschar** [comment]
Here we are, an initial draft version of the task edit form is done! 🥳 Three questions arised on the journey so far, hopefully someone of you guys can help out:

1. How do I force a width for the popover so it stays the same regardless of its content?
2. How do I force the popover to always be rendered on the left side of the task list (on top of the list-list)?
3. How do I enable vertical scrolling in the `Gtk.TextView`?

..... and here here some screenshots on how the current popover looks like (please note: right now it jumps around, depending on it's content):

![Screenshot from 2019-11-07 23 38 00@2x](https://user-images.githubusercontent.com/392542/68434556-875fc700-01b9-11ea-8912-d107a691e82c.png)
![Screenshot from 2019-11-07 23 38 11@2x](https://user-images.githubusercontent.com/392542/68434566-8cbd1180-01b9-11ea-8f52-1c0a5fffe6d1.png)

**Comment by alainm23** [comment]
1. Use
```
var scrolled = new Gtk.ScrolledWindow (null, null);
scrolled.hscrollbar_policy = Gtk.PolicyType.NEVER;
scrolled.width_request = 246;
scrolled.expand = true;
scrolled.add (box);
```

2. You can create an invisible widget at the end of your TaskRow and use `task_popover.set_relative_to (<invisible_widget>);`

3. Use
var scrolled = new Gtk.ScrolledWindow (null, null);
scrolled.height_request = 246;
scrolled.add (Gtk.TextView);

**Comment by marbetschar** [comment]
@alainm23 thank you very much for your help - highly appreciated!

Do you have any idea how I may force the `Gtk.ScrolledWindow` to not enlarge horizontally? I've embedded the `Gtk.TextView` in it and set it's `hscrollbar_policy` to `NEVER`.

But: If I load a large text in TextView and scroll vertically, the whole popover gets wider for each scroll attempt. Same thing if I enter text: As soon as the text width reaches the end, it should wrap - but right now it doesn't. It only makes the popover wider and wider.

The code is located here: https://github.com/elementary/tasks/blob/92873d0c5c835f86a9ccfc0850116a86a716aab3/src/Widgets/TaskSettingsPopover.vala#L59-L74

**Comment by marbetschar** [comment]
was able to get that resolved by setting `hscrollbar_policy = Gtk.PolicyType.EXTERNAL`. The minimal features of the task settings popover form are now done. Will create a pull request for it. Here's how it looks like right now:

![Screenshot von 2019-11-08 14 14 03](https://user-images.githubusercontent.com/392542/68479639-12c96e80-0233-11ea-82b3-316a2ef4c2e1.png)
