### ISSUE TITLE
UX improvements to edit tasks.

### ISSUE THREAD

**Issue by alainm23** [elementary/tasks#69]
1. Is it intuitive to double click on the task to edit it?
- Double clicking is fine, but we can add a button at the end of the task so that the edition is also activated (and have the Popover shown from this button)

2. Focus for the Gtk.Entry of the task name.
- When the popover is shown we can make the name of the task focus, this with the intention of making the edition faster.

**Comment by danrabbit** [comment]
I'm not a big fan of the double click personally. We don't normally use Double click other places, so I feel like this could at least be a single click. But in general, I'm not sure a popover is the right approach. It seems like more inline editing would be better. Planner seems to handle this a lot smoother

**Comment by marbetschar** [comment]
I just used the popover to get started, since I'm not too familiar yet with the possibilities of Gtk - and use Apple Reminders a lot. But the UX there is quite old fashioned.

That said +1 from me to get rid of the popover ;)

Inline editing seems much better. Also the way Planner does it is super cool!  The only thing there is, I'm not 100% convinced of the "transform to card" approach. It is maybe even smoother if we just slide the road down on selection to show the form - and preselect the summary entry.

**Comment by marbetschar** [comment]
```
|////////////////////////////////////////////|
|                                            |
| My Task List                           [:] |
|                                            |
|--------------------------------------------|
|                                            |
| [+] [___________________________________]  |    ← (1)
|                                            |
|--------------------------------------------|
|                                            |
|  ☐ Design needs improvement                |
|    The task app should be intiutive a...   |
|                                            |
| 🢒 ☐ Design Task App   ⬉                    |    ← (2)
|    (in 40min) The task app should be ...   |
|                                            |
|============================================|
| 🢓 ☐ The Edit UI                            |    ← (3)
|  This is the very long description, which  |
|  can span over multiple lines.             |
|                                            |
|  Lorem ipsum ... sit amet.                 |
|--------------------------------------------|
|  Schedule  ☐🗹   [ 1st Jan 📅][ 8:30 pm 🕑] |
|--------------------------------------------|
|  [ Delete ]               [Cancel] [Save]  |
|============================================|
|                                            |
|  ☐ Design needs improvement                |
|                                            |
|  ☐ Design needs improvement                |
|    The task app should be intiutive a...   |
|                                            |
|--------------------------------------------|
|                                            |
|////////////////////////////////////////////|
```
A first attempt to improve the task workflow:
(1): At the top below the list title there is an add row with a input field where the user is able to enter a new task title. As soon as this field is selected, the edit form expands there
(2): When the user hovers over a task, an arrow icon indicates that it's expandable
(3): The edit UI expands as soon as the user selects a task

Thoughts?

**Comment by marbetschar** [comment]
See PR https://github.com/elementary/tasks/pull/78 for the current state of inline editing.

**Comment by marbetschar** [comment]
Closing this in favour of https://github.com/elementary/tasks/issues/92 which reflects the current state of development. Discussion on how to further improve the design can be held there.
