### ISSUE TITLE
Delete an existing task

### ISSUE THREAD

**Issue by marbetschar** [elementary/tasks#77]
What the title says: We need to be able to delete an existing task.

**Comment by varunmurkar** [comment]
Hi @marbetschar ,

I'd like to take this up. Is there a current UI I can have a look at for reference?

**Comment by marbetschar** [comment]
Hi @varunmurkar,
Great! No existing UI right now, but in terms of functionality you might want to check the elementary Calendar app: https://github.com/elementary/calendar/blob/db2f86b16fd4765db66ba5d407964f161422b628/core/Model/CalendarModel.vala#L178

To begin with, you maybe just want to add a Delete button in the lower left of the edit popover. Similar to the Calendar app:

![Screenshot from 2020-01-19 19 13 44](https://user-images.githubusercontent.com/392542/72685980-dd24e980-3aef-11ea-8ada-dc92d4be7341.png)

We need to overhaul the edit UI anyways to get rid of the popover.

**Comment by marbetschar** [comment]
See https://github.com/elementary/tasks/pull/78 for a task inline-editing proposal which also contains a delete button.
