### ISSUE TITLE
Possible to drag header paned to very small size

### ISSUE THREAD

**Issue by danrabbit** [elementary/tasks#9]
![Screenshot from 2019-08-02 13 01 55@2x](https://user-images.githubusercontent.com/7277719/62395648-c7ae0a00-b525-11e9-9f66-dfd4949f180a.png)

**Comment by marbetschar** [comment]
@danrabbit is this issue still a thing? Never had this problem.

**Comment by danrabbit** [comment]
This is now fixed since we use a single paned
